name: Continuous Integration Workflow

# This workflow is triggered whenever a new pull request on push request  is created on the main branch
on:
  pull_request:
    branches:
      - main
    paths:
      - 'web/**' # this is for directory change 
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:

  # Run unit tests to make sure everything is 👍 (simple code test )
  test:
    name: 'Run unit tests'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow #folder name 
        working-directory: ./web  
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-latest
    # Define the steps for this job
    steps:
    - uses: actions/checkout@v2
      name: 'Checkout repository'

    - name: 'Install Dependencies'
      run: npm install
    
    - name: 'Run Tests'
      run: npm run test

  # Run the linter to check for code style issues   (code structure test)
  lint:
    name: 'Run linter'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
      name: 'Checkout repository'
    
    - name: 'Install Dependencies'
      run: npm install

    - name: 'Run Linter'
      run: npx standard -v
